=== ceyeep/CJC/iterators.dtd
<!ELEMENT iterators (iterator+)>
<!ELEMENT iterator (iteratorType,keyWord,element,arg?)>

<!ELEMENT iteratorType (#PCDATA)>
<!ELEMENT keyWord (#PCDATA)>
<!ELEMENT element (elemType,varName)>
<!ELEMENT arg (argType,varName)>

<!ELEMENT elemType (#PCDATA)>
<!ELEMENT argType (#PCDATA)>
<!ELEMENT varName (#PCDATA)>

=== ceyeep/CJC/iterators.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iterators SYSTEM "iterators.dtd">

<iterators>

  <iterator>
		<iteratorType>int</iteratorType>
        <keyWord>iterator</keyWord>
        <element>
			<elemType>int</elemType>
			<varName>x</varName>
		</element>
   </iterator>
   
   <iterator>
		<iteratorType>int</iteratorType>
        <keyWord>exists</keyWord>
        <element>
			<elemType>int</elemType>
			<varName>y</varName>
		</element>
		<arg>
			<argType>boolean</argType>
			<varName>z</varName>
		</arg>
   </iterator>
    
</iterators>
